"""
Task Queue — Priority and delayed execution queue for the Scheduler.
======================================================================

Provides a thread-safe, asynchronous priority queue for scheduled tasks.
Tasks are ordered by their scheduled execution time (earliest first)
and priority (higher priority executes first if times match).

Features:
    • Priority and time-based ordering
    • Async enqueue and dequeue (with blocking wait)
    • Thread-safe operations via asyncio locks
    • Support for retries and delayed execution
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger("pinterest_agent.scheduler.queue")


@dataclass(order=True)
class ScheduledTask:
    """A task waiting in the queue to be executed."""
    
    # Sort order: (run_at, -priority)
    # So earlier times pop first, and higher priority (e.g. 10 > 1) pops first
    run_at: float
    priority_invert: int = field(init=False)
    
    id: str = field(compare=False)
    name: str = field(compare=False)
    priority: int = field(compare=False, default=1)
    func_name: str = field(compare=False, default="")
    payload: dict[str, Any] = field(compare=False, default_factory=dict)
    
    is_recurring: bool = field(compare=False, default=False)
    cron_expr: str | None = field(compare=False, default=None)
    interval_sec: int | None = field(compare=False, default=None)
    
    status: str = field(compare=False, default="queued")
    retries: int = field(compare=False, default=0)

    def __post_init__(self) -> None:
        # Invert priority so higher numbers sort earlier in the queue
        self.priority_invert = -self.priority

    def to_dict(self) -> dict[str, Any]:
        """Serialize task for storage."""
        return {
            "id": self.id,
            "name": self.name,
            "run_at": self.run_at,
            "priority": self.priority,
            "func_name": self.func_name,
            "payload": self.payload,
            "is_recurring": self.is_recurring,
            "cron_expr": self.cron_expr,
            "interval_sec": self.interval_sec,
            "status": self.status,
            "retries": self.retries,
        }


class TaskQueue:
    """
    An asynchronous priority queue for scheduled tasks.
    """

    def __init__(self) -> None:
        # We use asyncio.PriorityQueue which handles the sorting naturally
        # based on the __lt__ implementation generated by dataclass(order=True)
        self._queue: asyncio.PriorityQueue[ScheduledTask] = asyncio.PriorityQueue()
        self._items: dict[str, ScheduledTask] = {}
        self._lock = asyncio.Lock()
        
        logger.info("TaskQueue initialized.")

    @property
    def size(self) -> int:
        """Return the number of tasks in the queue."""
        return self._queue.qsize()

    async def push(self, task: ScheduledTask) -> None:
        """
        Add a task to the queue.
        
        If a task with the same ID already exists, it is ignored to prevent duplicates.
        """
        async with self._lock:
            if task.id in self._items:
                logger.debug("Task '%s' already in queue, skipping.", task.id)
                return
                
            self._items[task.id] = task
            await self._queue.put(task)
            
        logger.debug(
            "Task enqueued  │  id=%s  name=%s  run_at=%.1f",
            task.id,
            task.name,
            task.run_at,
        )

    async def peek(self) -> ScheduledTask | None:
        """
        Look at the next task without removing it.
        Returns None if the queue is empty.
        """
        if self._queue.empty():
            return None
            
        # PriorityQueue doesn't have a peek, so we access the internal heap
        # Note: _queue[0] is the smallest element in heapq
        return self._queue._queue[0] if self._queue._queue else None  # type: ignore

    async def pop(self) -> ScheduledTask:
        """
        Remove and return the next task.
        Blocks if the queue is empty.
        """
        task = await self._queue.get()
        async with self._lock:
            self._items.pop(task.id, None)
            
        return task

    async def remove(self, task_id: str) -> bool:
        """
        Remove a task by ID.
        
        Since PriorityQueue doesn't support random deletion easily,
        we mark its status as 'cancelled'. It will be discarded when popped.
        """
        async with self._lock:
            task = self._items.get(task_id)
            if task:
                task.status = "cancelled"
                logger.info("Task cancelled in queue  │  id=%s", task_id)
                return True
        return False

    async def clear(self) -> None:
        """Wipe all tasks from the queue."""
        async with self._lock:
            self._items.clear()
            # Drain queue
            while not self._queue.empty():
                try:
                    self._queue.get_nowait()
                except asyncio.QueueEmpty:
                    break
        logger.debug("TaskQueue cleared.")
